require("custom.paths")
require("custom.autocmds")
require("custom.options")
require("custom.diagnostic")
require("custom.filetype")
require("manager.lazy")
-- require("custom.background")
vim.schedule(function()
	require("custom.remaps")
end)
